server.port=8080
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME_ENC}
spring.datasource.password=${DB_PASSWORD_ENC}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_batch_fetch_size=1000
spring.jpa.open-in-view=false
jasypt.encryptor.password=${JASYPT_ENCRYPTOR_PASSWORD}
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SEC
RET}
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri=${REDIRECT_URL}
api.key.secret=${API_KEY_SECRET}
logging.level.root=INFO
logging.level.com.example.demo=DEBUG
