
server.port=8080
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME_ENC}
spring.datasource.password=${DB_PASSWORD_ENC}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.default_batch_fetch_size=1000
spring.jpa.open-in-view=false

jasypt.encryptor.password=${JASYPT_ENCRYPTOR_PASSWORD}

jwt.secret=local-test-secret-key-darktrace-project-2026-fighting
jwt.expiration=3600000

logging.level.root=INFO
logging.level.com.example.demo=DEBUG