name: Backend CI/CD (AWS EC2)

on:
  push:
    branches: [ "main" ] # main 브랜치에 push 될 때 작동

jobs:
  deploy:
    runs-on: self-hosted # AWS 서버에서 직접 실행

    steps:
    - name: 1. 최신 코드 가져오기
      uses: actions/checkout@v3

    - name: 2. gradlew 실행 권한 부여
      run: chmod +x ./gradlew

    - name: 3. Spring Boot 프로젝트 빌드 (테스트 제외)
      run: ./gradlew clean build -x test

    - name: 4. 기존 실행 중인 서버 종료 (8080 포트)
      run: |
        sudo fuser -k -n tcp 8080 || true

    - name: 5. Jasypt 및 DB 환경변수 주입 후 새 서버 무중단 실행
      env:
        # 인프라 단에서 관리하는 GitHub Secrets에서 값을 꺼내옵니다.
        JASYPT_PASSWORD: ${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }}
        DB_URL: ${{ secrets.DB_URL }}
        DB_USER: ${{ secrets.DB_USERNAME_ENC }}
        DB_PASS: ${{ secrets.DB_PASSWORD_ENC }}
      run: |
        # 깃허브 액션이 백그라운드 프로세스 죽이지 못하게 추적 ID를 비우게함
        export RUNNER_TRACKING_ID=""
        
        # 환경변수를 Java 실행 파라미터(-D)로 안전하게 주입하여 실행 (쌍따옴표 추가)
        nohup java -jar \
          -DJASYPT_ENCRYPTOR_PASSWORD="$JASYPT_PASSWORD" \
          -DDB_URL="$DB_URL" \
          -DDB_USERNAME_ENC="$DB_USER" \
          -DDB_PASSWORD_ENC="$DB_PASS" \
          -Dspring.jpa.hibernate.ddl-auto=update \
          -Djwt.secret="$JWT_SECRET" \
          -Djwt.expiration=86400000 \
          build/libs/*SNAPSHOT.jar > application.log 2>&1 &
